version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112

functions:
  push-s3:
    lang: python3
    handler: ./push-s3
    image: alexellisuk/push-s3:latest
    environment:
      s3_hostname: kubecon.fra1.digitaloceanspaces.com
      s3_secure: true
    secrets:
    - access-key
    - secret-key
