version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  push-s3:
    lang: python3
    handler: ./push-s3
    image: alexellis2/push-s3:0.1.7
    environment:
      s3_bucket_name: "kubecon"
      s3_hostname: "fra1.digitaloceanspaces.com"
      s3_secure: true
      write_debug: true
      combine_output: false
    secrets:
    - access-key
    - secret-key
